export type Client = {
  address: string;
  mapped: boolean;
  hidden: boolean;
  visible: boolean;
  acceptsInput: boolean;
  at: [number, number];
  size: [number, number];
  workspace: {
    id: number;
    name: string;
  };
  floating: boolean;
  monitor: number;
  class: string;
  title: string;
  initialClass: string;
  initialTitle: string;
  pid: number;
  xwayland: boolean;
  pinned: boolean;
  fullscreen: number;
  fullscreenClient: number;
  overFullscreen: boolean;
  grouped: string[];
  tags: string[];
  swallowing: string;
  focusHistoryID: number;
  inhibitingIdle: boolean;
  xdgTag: string;
  xdgDescription: string;
  contentType: string;
  stableID: string;
};
